version: "3.9"

services:
  app:
    build: .
    container_name: store_map_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src          # 코드 변경 실시간 반영
      - /app/node_modules       # 컨테이너 내부 모듈 고정
    depends_on:
      - redis
      - db

  redis:
    image: redis:7-alpine
    container_name: store_map_redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: mariadb:11
    container_name: store_map_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: storedb
      MYSQL_USER: storeuser
      MYSQL_PASSWORD: storepw
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  redis_data:
  db_data:
